---
title: "Poster-Script"
author: "Anthony Chan"
date: "April 4, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r dependencies}
library(tidyverse)
library(rworldmap)
library(RColorBrewer)
```

```{r import_data}
df = read.csv("Online_Retail_Raw.csv")
df$total_price <- df$UnitPrice * df$Quantity
```

```{r remove_non_european}
#ONLY RUN IF YOU ONLY WANT EUROPEAN COUNTRIES
non_european <- c("Australia", "Bahrain", "Brazil", "Canada", "Hong Kong", "Israel", "Lebanon",
                  "Japan", "RSA", "Saudi Arabia", "Singapore", "United Arab Emirates",
                  "Unspecified", "USA")

df <- df[!(df$Country %in% non_european),]

df$Country <- factor(df$Country)

table(df$Country)
```

```{r}

```


```{r add_dates}
df$Dates <- format(as.POSIXct(strptime(df$InvoiceDate,"%m/%d/%Y %H:%M",tz="")) ,format = "%Y/%m")

```

```{r remove_bulk}
#RUN IF YOU WANT TO REMOVE BULK ORDERS
df <- df[df$Quantity <= 50 & df$Quantity >= 0,]

```

```{r}
by_country = split(df, f = df$Country)

#by_customer = split(df, f = df$CustomerID)

#by_invoice = split(df, f = df$InvoiceNo)

#by_item = split(df, f = df$StockCode)
```


```{r}
table(df$Country)

countries <- names(table(df$Country))
```

```{r}
median(df$Quantity)
```
```{r Q1}

#Generate the data
country_unit_price <- by_country %>%
  lapply(FUN = function(x) median(x$UnitPrice)) %>%
  stack() %>%
  rename(UnitPrice = values, Country = ind)
  
#Bind the data
unit_map <- joinCountryData2Map(country_unit_price, joinCode = "NAME",
                                nameJoinColumn = "Country")

mapParams <- mapCountryData(unit_map,
                            nameColumnToPlot = "UnitPrice",
                            xlim = c(-20,30),
                            ylim = c(30,70),
                            catMethod = "pretty",
                            mapTitle = "Median Unit Price Per Country(pounds)",
                            missingCountryCol = "grey",
                            colourPalette = brewer.pal(9, "Blues"),
                            addLegend = FALSE)

#customize the legend
do.call( addMapLegend, c(mapParams,
                         legendLabels = "all",
                         horizontal = TRUE))

```

```{r Quantity}
country_quantity <- by_country %>%
  lapply(FUN = function(x) median(x$Quantity)) %>%
  stack() %>%
  rename(Quantity = values, Country = ind)

table(by_country$Netherlands$Quantity)

#Bind the data
quant_map <- joinCountryData2Map(country_quantity, joinCode = "NAME",
                                nameJoinColumn = "Country")

mapParams <- mapCountryData(quant_map,
                            xlim = c(-20,30),
                            ylim = c(30,70),
                            nameColumnToPlot = "Quantity",
                            catMethod = "pretty",
                            mapTitle = "Median Quantity Per Country",
                            missingCountryCol = "grey",
                            colourPalette = brewer.pal(9, "Blues"),
                            addLegend = FALSE)

#customize the legend
do.call( addMapLegend, c(mapParams,
                         legendLabels = "all",
                         horizontal = TRUE))
```

```{r}

```

```{r total_price}
country_total <- by_country %>%
  lapply(FUN = function(x) sum(x$total_price)/length(unique(x$CustomerID))) %>%
  stack() %>%
  rename(total_spent = values, Country = ind)

#Bind the data
total_map <- joinCountryData2Map(country_total, joinCode = "NAME",
                                nameJoinColumn = "Country")

mapParams <- mapCountryData(total_map,
                            xlim = c(-20,30),
                            ylim = c(30,70),
                            nameColumnToPlot = "total_spent",
                            catMethod = "pretty",
                            mapTitle = "Customer Total Spent Per Country(pounds)",
                            missingCountryCol = "grey",
                            colourPalette = brewer.pal(9, "Blues"),
                            addLegend = FALSE)

#customize the legend
do.call( addMapLegend, c(mapParams,
                         legendLabels = "all",
                         horizontal = TRUE))
```


```{r}
date_freq <- function(df){
  result <- as.data.frame(table(df$Dates)/nrow(df))
}

country_freqs <- bind_rows(lapply(by_country, FUN = date_freq), .id = "Country") %>%
  rename(Month = Var1)
```

```{r, fig.width = 11}
ggplot(country_freqs, aes(x = Month, y = Freq, fill = Country)) +
  geom_bar(stat = "identity", position = "identity", alpha = 0.7) +
  scale_color_brewer(type = "qual", palette = "Paired") +
  labs(
    title = "% of Purchases Made for a Given Country per Month",
    y = "Percentage of Total"
  )
```

```{r}
library(zoo)

country_freqs$Month <- paste(country_freqs$Month, "01", sep = "/")

country_freqs$Month <- as.Date(country_freqs$Month, format = "%Y/%m/%d")

ggplot(country_freqs, aes(x = Month, y = Freq, color = Country)) + 
  geom_line() +   
  scale_x_date(date_breaks = "1 month", date_labels = "%m/%Y") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(
    title = "% of Purchases Made for a Given Country per Month",
    y = "Percentage of Total",
    x = "Month"
  )
```

```{r}
total_mean <- aggregate(country_freqs$Freq, list(country_freqs$Month), mean)%>%
  rename(Month = Group.1, Freq = x)

ggplot(total_mean, aes(x = Month, y = Freq)) + 
  geom_line(colour = "steelblue", size = 2) +   
  scale_x_date(date_breaks = "1 month", date_labels = "%m/%Y") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 11),
        axis.text.y = element_text(size = 11),
        axis.title = element_text(size = 12, face = "bold")) +
  labs(
    title = "% of Purchases Made per Month",
    y = "Percentage of Total",
    x = "Month"
  )

ggsave("mean_plot.jpg", device = "jpeg", path = "./", width = 10, height = 5)
```

```{r, fig.height=8, fig.width = 15}
country_freqs <- bind_rows(lapply(by_country, FUN = date_freq), .id = "Country") %>%
  rename(Month = Var1)

countries = c("United_Kingdom","Netherlands","Belgium","EIRE","France","Germany","Portugal","Spain","Switzerland")
country_freqs <- country_freqs[country_freqs$Country %in% countries,]

mean_country <- aggregate(country_freqs$Freq, list(country_freqs$Month), mean) %>%
  rename(Month = Group.1, Freq = x)

mean_country$Country <- "Mean"

country_freqs <- rbind(country_freqs, mean_country)

country_freqs$Month <- paste(country_freqs$Month, "01", sep = "/")

country_freqs$Month <- as.Date(country_freqs$Month, format = "%Y/%m/%d")

ggplot(country_freqs, aes(x = Month, y = Freq)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  scale_x_date(date_breaks = "2 month", date_labels = "%b") +
  facet_wrap(~Country, ncol = 3) +
  theme(axis.text.x = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        axis.text.y = element_text(size = 12),
        strip.text.x = element_text(size = 12, face = "bold"))

ggsave("country_freqs.jpg", device = "jpeg", path = "./", height = 8, width = 15)
```

```{r}
df$day <- weekdays(as.Date(df$InvoiceDate))

df = df[df$UnitPrice >= 0 & df$UnitPrice <= 10,]

df$price_bin <- cut(df$UnitPrice, breaks = c(0,2,6,Inf), labels = c("Low","Middle","High"))

df$total_price <- df$Quantity * df$UnitPrice

df.agg <- aggregate(df$total_price, by=list(df$day, df$price_bin), sum) %>%
  rename(Weekday = Group.1, price_bin = Group.2, total_spen = x)
```

